/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'on-primary-fixed': '#1b1b1b',
        'on-tertiary-fixed': '#001f28',
        'secondary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'tertiary-fixed-dim': '#4cd6ff',
        'on-secondary-fixed-variant': '#454747',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'tertiary-fixed': '#b7eaff',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'secondary-fixed': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#474747',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'on-tertiary-fixed-variant': '#004e60',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'surface-tint': '#c6c6c6',
        'inverse-on-surface': '#313030',
        'secondary': 'rgb(var(--color-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        'inverse-primary': '#5e5e5e',
        'error': '#ffb4ab',
        'on-background': 'rgb(var(--color-on-background) / <alpha-value>)',
        'outline': 'rgb(var(--color-outline) / <alpha-value>)',
        'on-error': '#690005',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'primary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1a1c1c',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'background': 'rgb(var(--color-background) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'tertiary': 'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'cyber-purple': '#BD00FF',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'gutter': '24px',
        'column-gap': '32px',
        'unit': '4px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'sans': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'display': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'code': ['JetBrains Mono', 'monospace'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        'code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
