/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'surface-bright': '#393939',
        'on-primary-fixed': '#1b1b1b',
        'on-tertiary-fixed': '#001f28',
        'secondary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        'surface': '#131313',
        'tertiary-fixed-dim': '#4cd6ff',
        'on-secondary-fixed-variant': '#454747',
        'surface-container-high': '#2a2a2a',
        'tertiary-fixed': '#b7eaff',
        'on-surface-variant': '#cfc4c5',
        'surface-variant': '#353535',
        'on-surface': '#e5e2e1',
        'surface-dim': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'secondary-fixed': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#474747',
        'primary': '#c6c6c6',
        'on-tertiary-container': '#00809d',
        'on-tertiary-fixed-variant': '#004e60',
        'tertiary-container': '#000000',
        'on-primary-container': '#757575',
        'surface-tint': '#c6c6c6',
        'inverse-on-surface': '#313030',
        'secondary': '#c6c6c7',
        'secondary-container': '#454747',
        'outline-variant': '#4c4546',
        'inverse-primary': '#5e5e5e',
        'error': '#ffb4ab',
        'on-background': '#e5e2e1',
        'outline': '#988e90',
        'on-error': '#690005',
        'on-secondary': '#2f3131',
        'primary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1a1c1c',
        'primary-container': '#000000',
        'surface-container-highest': '#353535',
        'inverse-surface': '#e5e2e1',
        'on-tertiary': '#003543',
        'on-primary': '#303030',
        'background': '#131313',
        'surface-container': '#20201f',
        'surface-container-low': '#1c1b1b',
        'tertiary': '#4cd6ff',
        'on-secondary-container': '#b4b5b5',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'gutter': '24px',
        'column-gap': '32px',
        'unit': '4px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'sans': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'display': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'code': ['JetBrains Mono', 'monospace'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        'code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
